#!/bin/sh

set -x

PAGES="training-day.html basic-tools.html conan-the-librarian.html"

git checkout gh-pages &&
git merge --no-edit master &&
rm -f $PAGES &&
redo &&
git commit -a -m "Update HTML." &&
git push

git checkout master
