#!/usr/bin/env zsh

SOURCES=(*.markdown)
PAGES=(${SOURCES/%.markdown/.html})

echo "Building $PAGES."

git checkout gh-pages                  &&
git clean -fx                          &&
GIT_MERGE_AUTOEDIT=no git merge master &&
rm -f $PAGES                           &&
redo                                   &&
if git commit --porcelain --all | grep -q '^M '; then
    git commit -a -m "Update HTML." &&
    git push
else
    echo No changes, skipping push.
fi

git checkout master
