#!/bin/sh

PAGES="training-day.html basic-tools.html conan-the-librarian.html"

git checkout gh-pages       &&
git merge --no-edit master  &&
rm -f $PAGES                &&
redo                        &&
if git commit --porcelain --all | grep -q '^M '; then
    git commit -a -m "Update HTML." &&
    git push
else
    echo No changes, skipping push.
fi

git checkout master
